const SHADERS_DIR = new URL("../shaders/", import.meta.url);

const glyph_chunk = await Deno.readTextFile(new URL("glyph.frag", SHADERS_DIR));

async function gen(name: string, kind: "vert" | "frag"): Promise<string> {
	let src = await Deno.readTextFile(new URL(`${name}.${kind}`, SHADERS_DIR));

	// replace the include block with the glyph chunk
	src = src.replace('#include "glyph.frag"', glyph_chunk);

	// e.g., terminal.vert -> export const terminal_vert = ...
	return `export const ${name}_${kind} = \`\\\n${src}\`;`;
}

const out = [
	"// generated by `deno task shaders`",
	await gen("terminal", "vert"),
	await gen("terminal", "frag"),
	await gen("renderer", "vert"),
	await gen("renderer", "frag"),
].join("\n\n") + "\n";

const OUT_FILE = new URL("../src/shaders.ts", import.meta.url);
await Deno.writeTextFile(OUT_FILE, out);
console.log(`Wrote ${OUT_FILE.pathname}`);
