const SHADERS_DIR = new URL("../shaders/", import.meta.url);

async function gen(name: string, kind: "vert" | "frag"): Promise<string> {
	const file_path = new URL(`${name}.${kind}`, SHADERS_DIR);
	const src = await Deno.readTextFile(file_path);

	// e.g., terminal.vert -> export const terminal_vert = ...
	return `export const ${name}_${kind} = \`\\\n${src}\`;`;
}

const out = [
	"// generated by `deno task shaders`",
	await gen("glyph", "frag"),
	await gen("terminal", "vert"),
	await gen("terminal", "frag"),
	await gen("renderer", "vert"),
	await gen("renderer", "frag"),
].join("\n\n") + "\n";

const OUT_FILE = new URL("../src/shaders.ts", import.meta.url);
await Deno.writeTextFile(OUT_FILE, out);
console.log(`Wrote ${OUT_FILE.pathname}`);
